language: node_js
node_js: "7"

os:
  - linux
  - osx
dist: trusty

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder

before_script:
  - npm prune
  - npm run rebuild

script:
  - npm run lint
  - npm run dist
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run coverage ; fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run report-coverage ; fi
